drop table persona if exists;

create table persona (
    id bigint generated by default as identity,
    nombre varchar(255) not null,
    primary key (id)
);

insert into
    persona (nombre)
    values
    ('Víctor'), ('Noelis');